#this is the name of the workflow
name: Hello

#runs on a trigger
on: 
  push:
    branches: [main]

#these are jobs inside the workflow
jobs:

#this is the name of the job

  greet:
  #this is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    env:
      MY_NAME: Nehal
    steps:
      - name: say hello to user
        run: echo "Hello Dosto"

      - name: say hello to Nehal
        run: echo "Hello $MY_NAME"
        
  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python & docker
        run: python --version && docker --version
  
        
  
